#!/bin/bash

#Gjør sånn at scriptet finner dependancy filer i smbgrabber mappa:
cd /home/kali/GitRepos/Infoskjerm/smbgrabber

#Loops over ips in raspberry pi ip setting range, 209-213 and display if they are online or not.
statusPi()
{
for ip in 10.164.62.{209..213}; do

	ping -c 1 -t 2 $ip > /dev/null 2> /dev/null

	if [ $? -eq 0 ]; then
		echo "$ip er online"
	else
		echo "${ip} er nede"
	fi
done
}

#uptimePi()
#{
#Does not work on arch linux, tried with pssh aswell but no go.
#parallel-ssh -h sshList -l pi -p 5 -x source uptimePi 1> testlog.log
#}

updatePi()
{
for ip in {209..213}; do
	ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.$ip sudo apt-get update -y &
done
}




upgradePi()
{
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.213 sudo apt-get upgrade -y &
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.212 sudo apt-get upgrade -y &
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.211 sudo apt-get upgrade -y &
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.210 sudo apt-get upgrade -y &
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.209 sudo apt-get upgrade -y &
}

rebootPi()
{
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.213 sudo reboot &
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.212 sudo reboot &
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.211 sudo reboot &
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.210 sudo reboot &
ssh -i /home/kali/GitRepos/infoskjerm/SSH_Keys/newruler.key pi@10.164.62.209 sudo reboot &
}

rssChecker()
{
echo "---------------------------------------------------------------------"
echo -e "Bygginn RSS feed ble skrevet: ":
stat -c '%y' /mnt/infoskjermer/bygginn/output.xml
echo "---------------------------------------------------------------------"
echo -e "Gyminn RSS feed ble skrevet:  ":
stat -c '%y' /mnt/infoskjermer/gyminn/output.xml
echo "---------------------------------------------------------------------"
echo -e "Hovedinn RSS feed ble skrevet:  ":
stat -c '%y' /mnt/infoskjermer/hovedinn/output.xml
echo "---------------------------------------------------------------------"
echo -e "Ekspidisjon RSS feed ble skrevet:  ":
stat -c '%y' /mnt/infoskjermer/ekspidisjon/output.xml
echo "---------------------------------------------------------------------"
echo -e "Kantina RSS feed ble skrevet:  ":
stat -c '%y' /mnt/infoskjermer/kantina/output.xml
echo "---------------------------------------------------------------------"


cp /mnt/infoskjermer/bygginn/output.xml /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/bygginnRSSOutput.xml
cp /mnt/infoskjermer/gyminn/output.xml /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/gyminnRSSOutput.xml
cp /mnt/infoskjermer/hovedinn/output.xml /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/hovedinnRSSOutput.xml
cp /mnt/infoskjermer/ekspidisjon/output.xml /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/ekspidisjonRSSOutput.xml
cp /mnt/infoskjermer/kantina/output.xml /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/kantinaRSSOutput.xml
diff -q --from-file /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/bygginnRSSOutput.xml /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/gyminnRSSOutput.xml /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/hovedinnRSSOutput.xml /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/ekspidisjonRSSOutput.xml /home/kali/GitRepos/Infoskjerm/smbgrabber/xmlCheck/kantinaRSSOutput.xml;
if [ $? -eq 0 ]; then
		echo "No diffrences between the RSS bars! :)"
else
		echo "FAKE news spotted, please run rssUpdater........."
fi
}

rssUpdater()
{
/usr/bin/python /home/kali/GitRepos/Infoskjerm/smbgrabber/feed.py
cp /home/kali/GitRepos/Infoskjerm/smbgrabber/output.xml /mnt/infoskjermer/bygginn/
cp /home/kali/GitRepos/Infoskjerm/smbgrabber/output.xml /mnt/infoskjermer/gyminn/
cp /home/kali/GitRepos/Infoskjerm/smbgrabber/output.xml /mnt/infoskjermer/hovedinn/
cp /home/kali/GitRepos/Infoskjerm/smbgrabber/output.xml /mnt/infoskjermer/ekspidisjon/
cp /home/kali/GitRepos/Infoskjerm/smbgrabber/output.xml /mnt/infoskjermer/kantina/

}

#uptime()
#{
#ssh -i ~/Documents/newruler.key pi@10.164.62.209 source testscript.sh >> uptime.log &
#wait
#cat uptime.log
#}

#Funksjon som sentrerer teksten i terminalen, den kan brukes ved kommandoen:
#display_center DinTxtFil.txt
display_centerFile()
{
    columns="$(tput cols)"
    while IFS= read -r line; do
        printf "%*s\n" $(( (${#line} + columns) / 2)) "$line"
    done < "$1"
}


#Funksjon som sentrerer text fra en gitt variabel\string.
#Fjernet printf statments pga dette bare er for og vise hvordan funksjonen kan brukes.
joke1()
{
joke1="What is the diffrence between a computer and a woman?"
	COLUMNS=$(tput cols)
printf "%*s\n" $(((${#joke1}+$COLUMNS)/2)) "$joke1"
}

joke2()
{
joke2="A woman will not accept a 3.5 inch floppy"
	COLUMNS=$(tput cols)
printf "%*s\n" $(((${#joke2}+$COLUMNS)/2)) "$joke2"
}

#Kjører 5 commandoer fra tekstfilen sshSS.txt parallelt med hverandre
sshParallel()
{
#parallel-ssh -p 5 -h sshList -l pi -x source screenshot.sh &> /dev/null
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.213 source screenshot.sh
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.212 source screenshot.sh
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.211 source screenshot.sh
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.210 source screenshot.sh
ssh -i /home/kali/GitRepos/Infoskjerm/SSH_Keys/newruler.key pi@10.164.62.209 source screenshot.sh


}

runPi()
{

#Viser logo samt bruker biblioteket "boxes" for og omringe teksten i screensweretaken.txt med acsii art.
#Starter ssh screenshot kopieringen i bakgrunnen
display_centerFile logo.sh
joke1
sshParallel
joke2



#Under er eksempel på en annen kommando, jeg fikk ikke denne til og fungere slik jeg ønsket så jeg byttet den ut med den over.
#parallel -j 5 < sshSS.txt &> /dev/null


#wait kommandoen sørger for at ssh kommandoene i sshSS.txt får tid til og fullføre før scriptet fortsetter.


echo ""
echo "					   Checking if samba shares are mounted......."
echo ""

#Deklarerer enn liste med navn til raspberriene
declare -a arr=("bygginn"
				"gyminn"
				"hovedinn"
				"ekspidisjon"
				"kantina")

#Looper gjennom navnelisten og sjekker om de er mounted under /proc/mounts
for mount in "${arr[@]}"
do
	if grep -qs "$mount" /proc/mounts; then
		echo "	  			       $mount is allready mounted and located @ /mnt/infoskjermer/$mount"

	elif [[ $mount = "bygginn" ]] && ! grep -qs "$mount" /proc/mounts
	then
		mount -t cifs //10.164.62.213/Home /mnt/infoskjermer/bygginn -o guest
 		echo "					   Bygginn samba share has been mounted and can be found in /mnt/infoskjermer/$mount"

	elif [[ $mount = "gyminn" ]] && ! grep -qs "$mount" /proc/mounts
	then
		mount -t cifs //10.164.62.212/Home /mnt/infoskjermer/gyminn -o guest
		echo "				   Gyminn samba share has been mounted and can be found in /mnt/infoskjermer/$mount"

	elif [[ $mount = "hovedinn" ]] && ! grep -qs "$mount" /proc/mounts
	then
		mount -t cifs //10.164.62.211/Home /mnt/infoskjermer/hovedinn -o guest
		echo "				   Hovedinn samba share has been mounted and can be found in /mnt/infoskjermer/$mount"

	elif [[ $mount = "ekspidisjon" ]] && ! grep -qs "$mount" /proc/mounts
	then
		mount -t cifs //10.164.62.210/Home /mnt/infoskjermer/ekspidisjon -o guest
		echo "				   Ekspidisjon samba share has been mounted and can be found in /mnt/infoskjermer/$mount"

	elif [[ $mount = "kantina" ]] && ! grep -qs "$mount" /proc/mounts
	then
		mount -t cifs //10.164.62.209/Home /mnt/infoskjermer/kantina -o guest
		echo "				   Kantina samba share has been mounted and can be found in /mnt/infoskjermer/$mount"

	else
		echo "				   Something went wrong, nothing happened...."
	fi

done

echo ""
echo ""
cat nukelogo


#Kopierer bilder fra raspberryer til lokal pc
cp /mnt/infoskjermer/bygginn/bygginnSS.png /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/
cp /mnt/infoskjermer/gyminn/gyminnSS.png /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/
cp /mnt/infoskjermer/hovedinn/hovedinnSS.png /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/
cp /mnt/infoskjermer/kantina/kantinaSS.png /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/
cp /mnt/infoskjermer/ekspidisjon/ekspidisjonSS.png /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/
cp /mnt/infoskjermer/gyminn/gyminnSS.png /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/
cp /mnt/infoskjermer/hovedinn/hovedinnSS.png /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/
cp /mnt/infoskjermer/kantina/kantinaSS.png /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/
cp /mnt/infoskjermer/ekspidisjon/ekspidisjonSS.png /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/

#Viser frem FEH acsii logo
display_centerFile fehlogo.sh


sleep 1
#Starter FEH's bildekarusell og looper gjennom alle bildene i mappen ~/smbgrabber/pics
/usr/bin/feh -Y -d -x -q -D 2 -B black -F -r -R 30 /home/kali/GitRepos/Infoskjerm/smbgrabber/pics/


}


while true
do
	clear
display_centerFile logo.sh
echo " 	        			   	   /*****************************/"
echo " 	        			   	   /*                           */"
echo " 	        			   	   /*  Made by: André Hansen ©  */"
echo " 	        			   	   /*                           */"
echo " 	        			   	   /*       Version: 1.0        */"
echo " 	        			   	   /*                           */"
echo " 	        			   	   /*****************************/"

echo ""

echo "					If at first if you don't succeed, call it version 1.0"

echo ""
display_centerFile myMenubox
	echo -e "\n"
	echo -e "Enter your selection: \c"
	read answer
	case "$answer" in
	1) runPi ;;
	2) rssChecker ;;
	3) rssUpdater ;;
	4) statusPi ;;
	5) updatePi ;;
	6) upgradePi ;;
	7) rebootPi ;;
	q) exit ;;
esac
echo -e "Enter return to continue \c"
read input
done
